### ISSUE TITLE
Is foreground color determined by the ID's hash?

### ISSUE THREAD

**Issue by RoxKilly** [bitverseio/identicon#8]
hello,

Looking for an identicon library, I ran into this as well as [yzalis'](https://github.com/yzalis/Identicon/blob/master/src/Identicon/Identicon.php) so I've been trying to figure out which fits my needs best. 

The other package's identicon color is determined, like the design, by the hashed identity (eg: username).  Your `readme` doesn't mention how the foreground color is determined.  Is it set as a property of the class? Is it a function of the hash?  Do all identicons have the same color?

The only info in the readme that I see about color is how to set the background color:

```
$generator->setBackgroundColor(Color::parseHex('#EEEEEE'));
```

If the background color isn't set, what will it be?

**Comment by ice9js** [comment]
Yes, the foreground color is determined by the hash by default.

However, #6 introduced support for setting the foreground color manually if that's what you'd like. It works just like setting the background color:

``` php
$generator->setForegroundColor(Color::parseHex("#FFFFFF"));
```

**Comment by RoxKilly** [comment]
I understand.  If the background color isn't set, what will it be? I bet transparent, but don't want to assume.

**Comment by ice9js** [comment]
Actually, the library will crash if you don't provide a background color. Adding support for transparent backgrounds is simple, but I'm not sure if it would really be that useful.

If you happen to use [the identicon symfony bundle](https://github.com/bitverseio/BitverseIdenticonBundle), the default background color is set to `#EEEEEE`.

**Comment by RoxKilly** [comment]
OK you've answered all my Qs. If you have time, let me know why it would not be useful to have transparent bgs?  (I don't use Symfony; I would just use your classes directly).

Feel free to close the issue.

**Comment by ice9js** [comment]
I think it would make the icons look and feel very weird, but that's just a personal opinion to be honest.  It's easy to implement though, if that's something you feel like someone could use.
